CREATE DATABASE BIBLIOTECAPRACTICA;
USE BIBLIOTECAPRACTICA;

-- Tabla CLIENTES
CREATE TABLE CLIENTES (
    CLIENTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TEL VARCHAR(50) NOT NULL UNIQUE,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL UNIQUE
);

-- Tabla LIBROS
CREATE TABLE LIBROS (
    LIBRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    STOCK INT NOT NULL CHECK (STOCK >= 0),
    PRECIO DECIMAL(10,2) NOT NULL CHECK (PRECIO > 0)
);

-- Tabla PRESTAMOS
CREATE TABLE PRESTAMOS (
    PRESTAMO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_LIBRO INT NOT NULL,
    FECHA_PRESTAMO DATE NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS(LIBRO_ID) ON DELETE CASCADE
);

-- Trigger para validar stock antes de prestar
DELIMITER //
CREATE TRIGGER VALIDAR_STOCK
BEFORE INSERT ON PRESTAMOS
FOR EACH ROW
BEGIN
    DECLARE STOCK_DISPONIBLE INT;

    SELECT STOCK INTO STOCK_DISPONIBLE
    FROM LIBROS
    WHERE LIBRO_ID = NEW.ID_LIBRO;

    IF NEW.CANTIDAD > STOCK_DISPONIBLE THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'No hay suficiente stock para realizar el préstamo.';
    END IF;
END;
//
DELIMITER ;
